# Generated by Django 4.2.10 on 2024-03-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturaPlantada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Cultura plantada',
                'verbose_name_plural': 'Culturas plantada',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProdutorRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.IntegerField(default=0, verbose_name='CPF ou CNPJ')),
                ('nome_produtor', models.CharField(max_length=150, verbose_name='Nome do produtor')),
                ('nome_fazenda', models.CharField(max_length=150, verbose_name='Nome da fazenda')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('area_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Área total em hectares da fazenda')),
                ('area_agricultavel', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Área agricultável em hectares')),
                ('area_vegetacao', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Área de vegetação em hectares')),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culturaplantada', to='brain_ag.culturaplantada', verbose_name='Cultura plantada')),
            ],
        ),
    ]
