# Generated by Django 4.2.10 on 2024-03-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain_ag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturaplantada',
            options={'ordering': ['name'], 'verbose_name': 'Cultura plantada', 'verbose_name_plural': 'Culturas plantadas'},
        ),
    ]
