# Generated by Django 4.2.10 on 2024-03-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_ag', '0002_alter_culturaplantada_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtorrural',
            name='cultura',
        ),
        migrations.AddField(
            model_name='produtorrural',
            name='cultura',
            field=models.ManyToManyField(to='brain_ag.culturaplantada'),
        ),
    ]
