# Generated by Django 4.2.10 on 2024-03-02 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brain_ag', '0003_remove_produtorrural_cultura_produtorrural_cultura'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtorrural',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtorrural',
            name='cpf_cnpj',
            field=models.CharField(max_length=150, unique=True, verbose_name='CPF ou CNPJ'),
        ),
    ]
