# Generated by Django 4.2.10 on 2024-03-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_ag', '0004_produtorrural_submitter_alter_produtorrural_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtorrural',
            name='area_agricultavel',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Área agricultável em hectares'),
        ),
        migrations.AlterField(
            model_name='produtorrural',
            name='area_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Área total em hectares da fazenda'),
        ),
        migrations.AlterField(
            model_name='produtorrural',
            name='area_vegetacao',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Área de vegetação em hectares'),
        ),
        migrations.AlterField(
            model_name='produtorrural',
            name='cpf_cnpj',
            field=models.CharField(max_length=50, unique=True, verbose_name='CPF ou CNPJ'),
        ),
    ]
