# Generated by Django 4.2.10 on 2024-03-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain_ag', '0005_alter_produtorrural_area_agricultavel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtorrural',
            options={'ordering': ['nome_produtor', 'nome_fazenda', 'estado', 'cidade'], 'verbose_name': 'Nome do produtor', 'verbose_name_plural': 'Nomes dos produtores'},
        ),
    ]
